#=================================================
# Description: Build ubports using GitHub Actions
# Lisence: MIT
# Contributor: 0312birdzhang
# Maintainer: Danct12
# Credit: https://github.com/P3TERX/Actions-OpenWrt
#=================================================

name: Build System Image

on:
  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
        tags:
          description: 'Test scenario tags'  

  push:
    branches:
      - master
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-18.04

    env:
      VENDOR: xiaomi
      DEVICE: mido
      ANDROID_ROOT: /home/runner/work/halium/

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Initialization environment
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt install -y git gnupg flex bison gperf build-essential \
        zip bzr curl libc6-dev libncurses5-dev:i386 x11proto-core-dev \
        libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa-glx:i386 \
        libgl1-mesa-dev g++-multilib mingw-w64-i686-dev tofrodos \
        python-markdown libxml2-utils xsltproc zlib1g-dev:i386 schedtool \
        repo liblz4-tool bc lzop imagemagick libncurses5 rsync
        sudo docker rmi `docker images -q`
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        mkdir -p ~/bin
        wget 'https://storage.googleapis.com/git-repo-downloads/repo' -P ~/bin
        chmod +x ~/bin/repo
        git config --global user.name "UBports Redmi Note 4 CI"
        git config --global user.email "thisemaildoesnotexist@exist.com"

    - name: Downloading source code
      run: |
        source halium.env
        mkdir -p $ANDROID_ROOT
        cd $ANDROID_ROOT
        repo init -u https://github.com/Halium/android -b halium-7.1 --depth=1
        mkdir -p $ANDROID_ROOT/.repo/local_manifests
        wget https://raw.githubusercontent.com/ubports-mido/halium-devices/halium-7.1/manifests/"$VENDOR"_"$DEVICE".xml -O $ANDROID_ROOT/.repo/local_manifests/$DEVICE.xml
        repo sync -j8 -c --no-clone-bundle --no-tags
    
    - name: Build HAL
      run: |
        chmod +x build-hal.sh
        bash -x build-hal.sh
      shell: bash

    - name : Upload boot image
      uses: actions/upload-artifact@master
      with:
        name: halium-boot image
        path: /home/runner/work/halium/out/target/product/mido/halium-boot.img

    - name : Upload system image
      uses: actions/upload-artifact@master
      with:
        name: System image
        path: /home/runner/work/halium/out/target/product/mido/system.img
